/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Controlador;
import Vista.*;
import javax.swing.JInternalFrame;
/**
 *
 * @author xaviera
 */
public class MDIPrincipal extends javax.swing.JFrame {

    private JInternalFrameClientes Clientes;
    private JInternalFrameReserva Reserva;
    private JInternalFrameDestino Destinos;
    private JInternalFrameDetallesPaquetes DetallesPaquetes;
    private JInternalFramePaquetes Paquetes;
    /**
     * Creates new form SistemaPublicacionesMDI
     */
    public MDIPrincipal() {
        initComponents();
        setTitle("Clientes");
        Clientes= new JInternalFrameClientes();
        desktopPane.add(Clientes);
    
        setTitle("Reserva");
        Reserva= new JInternalFrameReserva();
        desktopPane.add(Reserva);

        setTitle("Destino");
        Destinos = new JInternalFrameDestino();
        desktopPane.add(Destinos);
        
        setTitle("Paquetes");
        Paquetes = new JInternalFramePaquetes();
        desktopPane.add(Paquetes);
        
        setTitle("Detalles Paquetes");
        DetallesPaquetes = new JInternalFrameDetallesPaquetes();
        desktopPane.add(DetallesPaquetes);
        
 
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        editMenu = new javax.swing.JMenu();
        verClientesMenuItem = new javax.swing.JMenuItem();
        ReservasMenuItem = new javax.swing.JMenuItem();
        DestinoMenuItem = new javax.swing.JMenuItem();
        PaquetesMenuItem = new javax.swing.JMenuItem();
        DetallesPaquetesMenuItem1 = new javax.swing.JMenuItem();
        HistorialMenuItem2 = new javax.swing.JMenuItem();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(102, 204, 255));

        editMenu.setMnemonic('e');
        editMenu.setText("Registro");

        verClientesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sexox (2).png"))); // NOI18N
        verClientesMenuItem.setMnemonic('t');
        verClientesMenuItem.setText("Clientes");
        verClientesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verClientesMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(verClientesMenuItem);

        ReservasMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/xavi (1).png"))); // NOI18N
        ReservasMenuItem.setMnemonic('y');
        ReservasMenuItem.setText("Reserva");
        ReservasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservasMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(ReservasMenuItem);

        DestinoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pepe (1).png"))); // NOI18N
        DestinoMenuItem.setMnemonic('p');
        DestinoMenuItem.setText("Destino");
        DestinoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(DestinoMenuItem);

        PaquetesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mmmmm (1).png"))); // NOI18N
        PaquetesMenuItem.setMnemonic('d');
        PaquetesMenuItem.setText("Paquetes");
        PaquetesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaquetesMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(PaquetesMenuItem);

        DetallesPaquetesMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aaaaa (1).png"))); // NOI18N
        DetallesPaquetesMenuItem1.setText("Detalle paquetes");
        DetallesPaquetesMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetallesPaquetesMenuItem1ActionPerformed(evt);
            }
        });
        editMenu.add(DetallesPaquetesMenuItem1);

        HistorialMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/historial (1).png"))); // NOI18N
        HistorialMenuItem2.setText("Historial");
        HistorialMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialMenuItem2ActionPerformed(evt);
            }
        });
        editMenu.add(HistorialMenuItem2);

        menuBar.add(editMenu);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Salir");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void verClientesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verClientesMenuItemActionPerformed
        // TODO add your handling code here:
       Clientes.obtenerDatos();
       Clientes.setVisible(true);
    }//GEN-LAST:event_verClientesMenuItemActionPerformed

    private void ReservasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservasMenuItemActionPerformed
        // TODO add your handling code here:
     Reserva.ObtenerDatos();
     Clientes.setVisible(true);
    }//GEN-LAST:event_ReservasMenuItemActionPerformed

    private void DestinoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinoMenuItemActionPerformed
        // TODO add your handling code here:
        Destinos.obtenerDatos();
        Destinos.setVisible(true);
    }//GEN-LAST:event_DestinoMenuItemActionPerformed

    private void PaquetesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaquetesMenuItemActionPerformed
        // TODO add your handling code here:
        Paquetes.obtenerDatos();
        Paquetes.setVisible(true);
    }//GEN-LAST:event_PaquetesMenuItemActionPerformed

    private void DetallesPaquetesMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetallesPaquetesMenuItem1ActionPerformed
        // TODO add your handling code here:
        DetallesPaquetes.obtenerDatos();
        DetallesPaquetes.setVisible(true);
    }//GEN-LAST:event_DetallesPaquetesMenuItem1ActionPerformed

    private void HistorialMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HistorialMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DestinoMenuItem;
    private javax.swing.JMenuItem DetallesPaquetesMenuItem1;
    private javax.swing.JMenuItem HistorialMenuItem2;
    private javax.swing.JMenuItem PaquetesMenuItem;
    private javax.swing.JMenuItem ReservasMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem verClientesMenuItem;
    // End of variables declaration//GEN-END:variables

}
